// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk94YB8FYC_eABwSjhTF5Rq-okmtoXgp0',
    appId: '1:1081346852166:android:657e03d51c7b7698b31147',
    messagingSenderId: '1081346852166',
    projectId: 'cloud-functions-get-star-4e4ba',
    storageBucket: 'cloud-functions-get-star-4e4ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdm5_r-55XlbsMtb3AMdOA768ig_hspWg',
    appId: '1:1081346852166:ios:88c2286c1034c3c4b31147',
    messagingSenderId: '1081346852166',
    projectId: 'cloud-functions-get-star-4e4ba',
    storageBucket: 'cloud-functions-get-star-4e4ba.firebasestorage.app',
    iosClientId: '1081346852166-fpvorllgpd74f99a9d99sa7t39f2vu4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseReadEmailClient',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtcfWMPUl_0VtmYZSOSibTWELV_mMyZVs',
    appId: '1:1081346852166:web:f45eeb4b0fd94a66b31147',
    messagingSenderId: '1081346852166',
    projectId: 'cloud-functions-get-star-4e4ba',
    authDomain: 'cloud-functions-get-star-4e4ba.firebaseapp.com',
    storageBucket: 'cloud-functions-get-star-4e4ba.firebasestorage.app',
    measurementId: 'G-5S0TEMB70Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdm5_r-55XlbsMtb3AMdOA768ig_hspWg',
    appId: '1:1081346852166:ios:88c2286c1034c3c4b31147',
    messagingSenderId: '1081346852166',
    projectId: 'cloud-functions-get-star-4e4ba',
    storageBucket: 'cloud-functions-get-star-4e4ba.firebasestorage.app',
    iosClientId: '1081346852166-fpvorllgpd74f99a9d99sa7t39f2vu4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseReadEmailClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtcfWMPUl_0VtmYZSOSibTWELV_mMyZVs',
    appId: '1:1081346852166:web:97638eab140b32feb31147',
    messagingSenderId: '1081346852166',
    projectId: 'cloud-functions-get-star-4e4ba',
    authDomain: 'cloud-functions-get-star-4e4ba.firebaseapp.com',
    storageBucket: 'cloud-functions-get-star-4e4ba.firebasestorage.app',
    measurementId: 'G-W3BZHW4ELC',
  );

}